/** Copyright 2022 Andrew J Bowley

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License. */
package au.com.cybersearch2.taq.db.h2;

import java.lang.reflect.InvocationTargetException;
import java.security.ProviderException;
import java.sql.Connection;
import java.util.Properties;

import au.com.cybersearch2.taq.db.ConnectionProfile;
import au.com.cybersearch2.taq.db.DbType;
import au.com.cybersearch2.taq.db.MethodAnalyser;
import au.com.cybersearch2.taq.query.QueryExecutionException;

/**
 * Characteristics of H2
 */
public class H2 implements DbType {

	@Override
	public String getJdbcPrefix() {
		return "jdbc:h2:";
	}

	@Override
	public String getJdbcInMemory() {
		return "jdbc:h2:mem";
	}

	@Override
	public String getType(Class<?> fieldClass, Class<?> entityClass) throws QueryExecutionException {
		String type = null;
		String typeName = fieldClass.getName();
		switch (typeName) {
		case "java.lang.String":
			type = "TEXT"; break;
		case "boolean":
		case "java.lang.Boolean":
			type = "BOOLEAN"; break;
		case "int":
		case "java.lang.Integer":
			type = "INTEGER"; break;
		case "long":
		case "java.lang.Long":
			type = "BIGINT"; break;
		case "double":
		case "java.lang.Double":
			type = "DOUBLE"; break;
		case "java.math.BigDecimal":
			type = "NUMERIC"; break;
		case "[B":
			type = "BLOB"; break;
		case "java.util.Date":
		case "java.sql.Date":
		    type = "DATE"; break;
		default:
			if (fieldClass.isEnum())
				type = "TEXT";
			else if (MethodAnalyser.isSerializable(fieldClass))
				type = "BLOB";
		}       
		if (type == null)
			throw new QueryExecutionException(String.format("Java type %s not supported", typeName));
		return type;
	}

	@Override
	public void appendIdentity(StringBuilder sql, boolean isAutoIncrement) {
		if (isAutoIncrement)
			sql.append(" GENERATED BY DEFAULT AS IDENTITY");
		sql.append(" PRIMARY KEY");
	}

	@Override
	public Connection getConnection(ConnectionProfile profile, Properties properties) {
		try {
			Class<?> driverClass = Class.forName("org.h2.jdbc.JdbcConnection");
			try {
				return (Connection) driverClass.getConstructor(String.class, java.util.Properties.class, String.class, Object.class, boolean.class)
					.newInstance(getJdbcPrefix() + profile.getDatabasePath(), properties, profile.getUser(), profile.getPassword(), false);
			} catch (InstantiationException | IllegalAccessException | IllegalArgumentException
					| InvocationTargetException | NoSuchMethodException | SecurityException e) {
				throw new ProviderException("Error creating H2 driver", e);
			}
		} catch (ClassNotFoundException e) {
			throw new ProviderException("H2 driver not found", e);
		}
	}
}
