/** Copyright 2022 Andrew J Bowley

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License. */
package agriculture;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

/**
 * AgriAreaPercent
 * Entity for percent of area under agriculture for one country
 * @author Andrew Bowley
 * 24Jan.,2017
 */
@Entity(name = "AgriAreaPercent")
public class AgriAreaPercent
{
	public static final String SURFACE_AREA_TERM = "surface_area_Km2";
	public static final int DECADE_COUNT = 201 - 196;
	
    /** This id is generated by the database and set on the object when it is passed to the create method */
    @Id @GeneratedValue
    int id;

    @Column(name = "country", nullable = false)
    String country;
    @Column(name = SURFACE_AREA_TERM, nullable = false)   
    double surfaceAreaKm2;
    @Column(name = "Y1970")
    double y1970;
    @Column(name = "Y1980")
    double y1980;
    @Column(name = "Y1990")
    double y1990;
    @Column(name = "Y2000")
    double y2000;
    @Column(name = "Y2010")
    double y2010;
    
    /**
     * @return the country name
     */
    public String getCountry() 
    {
        return country;
    }

    /**
     * @param country the country name to set
     */
    public void setCountry(String country) 
    {
        this.country = country;
    }

	public double getSurfaceAreaKm2() {
		return surfaceAreaKm2;
	}

	public void setSurfaceAreaKm2(double surfaceAreaKm2) {
		this.surfaceAreaKm2 = surfaceAreaKm2;
	}

	public double getY1970() {
		return y1970;
	}
	public void setY1970(double y1970) {
		this.y1970 = y1970;
	}
	public double getY1980() {
		return y1980;
	}
	public void setY1980(double y1980) {
		this.y1980 = y1980;
	}
	public double getY1990() {
		return y1990;
	}
	public void setY1990(double y1990) {
		this.y1990 = y1990;
	}
	public double getY2000() {
		return y2000;
	}
	public void setY2000(double y2000) {
		this.y2000 = y2000;
	}
	public double getY2010() {
		return y2010;
	}
	public void setY2010(double y2010) {
		this.y2010 = y2010;
	}

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}
	
	
}
