/** Copyright 2022 Andrew J Bowley

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License. */
package agriculture;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;

/**
 * Agri20Year
 * @author Andrew Bowley
 * 19 Mar 2015
 */
@Entity(name = "Agri20Year")
public class Agri20Year 
{
	static public final String COUNTRY_TERM = "country";
	static public final String SURFACE_AREA_TERM = "surface_area";
    
	public Agri20Year() 
	{
	}

	/** This id is generated by the application */
    @Id
 	int id;

    @Column(name = COUNTRY_TERM, nullable = false)
    String country;
	
	@Column(name = SURFACE_AREA_TERM, nullable = false)
	double surfaceArea;

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public double getSurfaceArea() {
		return surfaceArea;
	}

	public void setSurfaceArea(double surfaceArea) {
		this.surfaceArea = surfaceArea;
	}

	/**
	 * @return the country name
	 */
	public String getCountry () 
	{
		return country;
	}

	/**
	 * @param country the country name to set
	 */
	public void setCountry(String country) 
	{
		this.country = country;
	}
	
	
}
