/** Copyright 2022 Andrew J Bowley

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License. */
package agriculture;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

/**
 * Country
 * @author Andrew Bowley
 * 10 Feb 2015
 */
@Entity(name="Country")
public class Country 
{

	public static final String COUNTRY = "country";

	public Country() 
	{
	}

	public Country(String country) 
	{
		this.country = country;
	}

	/** This id is generated by the database and set on the object when it is passed to the create method */
    @Id @GeneratedValue
 	int id;

	@Column(name="country", nullable = false)
	String country;

	@Column(name=AgriAreaPercent.SURFACE_AREA_TERM)
	public long surfaceAreaKm2;
	
	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getCountry() {
		return country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public long getSurfaceAreaKm2() {
		return surfaceAreaKm2;
	}

	public void setSurfaceAreaKm2(long surfaceAreaKm2) {
		this.surfaceAreaKm2 = surfaceAreaKm2;
	}

}
